build:
  command: npm run build
  publish: dist
  NODE_ENV: 10.15.3

plugins:
  - ./plugins/rss-data-fetch:
      feeds:
        # - name: used as a key for accessing date later
        #   url: where to find this resource, in xml or json format
        #   ttl: don't fetch this again if cached less than this many seconds ago
        - name: hawksworx
          url: https://hawksworx.com/feed.json
          ttl: 180
        - name: netlify
          url: https://www.netlify.com/blog/index.xml
          ttl: 3600
        - name: dwells
          url: https://davidwells.io/rss.xml
          ttl: 180

  - ./plugins/rss-data-for-eleventy:
      data_dir: src/site/_data
