build:
  command: npm run build
  publish: dist
  functions: src/functions
  NODE_ENV: 10.15.3

plugins:
  - ./plugins/get-rss:
      # right now the syntax needs to have items in order to work.
      # But we can also add options here
      #enabled: true
      # someEnv: ${env.myEnv, 'default_or_fallback'}
      feeds:
        - name: hawksworx
          url: https://hawksworx.com/feed.json
          ttl: 3600 # don't get it again if cached less than this many seconds ago
        # - netlify: https://www.netlify.com/blog/index.xml
